# **Basics of the R language: II.1 - Linear Algebra**
### AJ Zerouali, 2023/06/01

This notebook looks at more advanced uses of R:

1) Dataframes
2) Plotting graphs
3) Linear algebra
4) Time series analysis

I should add something about basic stats in R, say Ch.7 of Kabacoff, but this is overkill in my case.

References:
- Dataframes: Kabacoff, Ch.3.
- Plotting graphs: Kabacoff, Chapters 4 and 6.
- Linear algebra: Youtube video: 
- Time series analysis: Kabacoff, Ch.15. 

## 3) Linear algebra with R

Here we leave Kkabacoff for a bit.

This playlist is an R introduction course on Youtube:

https://www.youtube.com/watch?v=fJ8q8cMur4o&list=PLW1_9UnhaSkE65XQ9n5TVkWeucU8txMNL&ab_channel=Let%27sLearn%2CNemo%21

In particular, we'll follow this lecture on linear algebra:

https://www.youtube.com/watch?v=VjYS59FoDYg&t=373s&ab_channel=Let%27sLearn%2CNemo%21

For the part on solving linear systems, we will use the *matlib* package (that I don't install by default).

https://cran.r-project.org/web/packages/matlib/index.html



### 3.a - Matrix algebra and elementary functions

Let's start with a simple invertible matrix:

        4	-1	6
    A = 2	 1	6
        2	-1	8


In [ ]:
# Columns
Ac1 <- c(4,2,2)
Ac2 <- c(-1,1,-1)
Ac3 <- c(6,6,8)

A <- matrix(c(Ac1, Ac2, Ac3), nrow =3, ncol = 3, byrow = FALSE)

cat("A = \n")
print(A)

A = 
     [,1] [,2] [,3]
[1,]    4   -1    6
[2,]    2    1    6
[3,]    2   -1    8


To create a diagonal matrix from a vector, we use the ***diag()*** function:

In [ ]:
# Create a doagonal matrix 
B <- diag(c(2,3,5))

Transposition and determinant computation are done like so:

In [ ]:
# Get transpose of a matrix
cat("A^T = \n")
t(A)

# Get determinant of a matrix
cat("det(A) = \n")
det(A)

A^T = 


[,1] [,2] [,3]
[1,]  4   2     2  
[2,] -1   1    -1  
[3,]  6   6     8

det(A) = 


[1] 36

Strangely enough, R does not seem to have a built-in trace method by default. 

Matrix inversion is done using *solve()*:

In [ ]:
# Invert the matrix A
cat("A^(-1) = \n")
solve(A)

A^(-1) = 


[,1]       [,2]       [,3]      
[1,]  0.3888889 0.05555556 -0.3333333
[2,] -0.1111111 0.55555556 -0.3333333
[3,] -0.1111111 0.05555556  0.1666667

Scalar multiplication is more or less obvious:

In [ ]:
10*A

[,1] [,2] [,3]
[1,] 40   -10  60  
[2,] 20    10  60  
[3,] 20   -10  80

Matrix multiplication is done using the symbol **%*%**:

In [ ]:
# Matrix multiplications
cat("A %*% B = \n")
print(A %*% B)
cat("B %*% A = \n")
print(B %*% A)

A %*% B = 
     [,1] [,2] [,3]
[1,]    8   -3   30
[2,]    4    3   30
[3,]    4   -3   40
B %*% A = 
     [,1] [,2] [,3]
[1,]    8   -2   12
[2,]    6    3   18
[3,]   10   -5   40


R does not have a built-in dot product either. It is not complicated however. Here is an example:

In [ ]:
# Vectors
u <- c(cos(pi/6), 0, sin(pi/6))
e3 <- c(0,0,1)

# Compute the norm of (cos(pi/6), 0, sin(pi/6))
cat("u.u = ")
(u %*% u)[1]
# Dot product of u and e3
cat("u.e3 = ")
(u %*% e3)[1]


u.u = 

[1] 1

u.e3 = 

[1] 0.5

Before moving-on to eigenvalues and eigenvectors, it's useful to note that matrix operations are not very accurate by default in R. Say we multiply our previous matrix $A$ by its inverse:

In [ ]:
A_inv <- solve(A)

cat("A.A^(-1) = \n")
print(A %*% A_inv)

cat("A^(-1).A = \n")
print(A_inv %*% A)

A.A^(-1) = 
              [,1] [,2] [,3]
[1,]  1.000000e+00    0    0
[2,] -1.110223e-16    1    0
[3,]  0.000000e+00    0    1
A^(-1).A = 
             [,1]         [,2]         [,3]
[1,] 1.000000e+00 5.551115e-17 0.000000e+00
[2,] 1.110223e-16 1.000000e+00 4.440892e-16
[3,] 0.000000e+00 0.000000e+00 1.000000e+00


We see some residual numerical errors in both cases. If needed, it would be a good idea to use the *round()* function (see https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Round):

In [ ]:
cat("A.A^(-1) = \n")
print(round(A %*% A_inv, 6)) # Round to 6 decimals

cat("A^(-1).A = \n")
print(round(A_inv %*% A, 6))

A.A^(-1) = 
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1
A^(-1).A = 
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


### 3.b - Eigenvalues and eigenvectors, diagonalization

Obtaining the eigenvectors and eigenvalues of a matrix is done with the ***eigen()*** function, which returns a list:

In [ ]:
# Get eigen-elements of A
eig_A <- eigen(A)

# Show eig_A structure
str(eig_A)

List of 2
 $ values : num [1:3] 9 2 2
 $ vectors: num [1:3, 1:3] 0.577 0.577 0.577 0.292 0.886 ...
 - attr(*, "class")= chr "eigen"


This example matrix $A$ is diagonalizable. We can use the usual decomposition $P\cdot D\cdot P^{-1}$ to check:

In [ ]:
# Get diagonal matrix and change of basis matrix:
A_D <- diag(eig_A$values)
A_P <- eig_A$vectors

# Compute the product decomposition
cat("P.D.P^(-1) = ")
print(A_P %*% A_D %*% solve(A_P))


P.D.P^(-1) =      [,1] [,2] [,3]
[1,]    4   -1    6
[2,]    2    1    6
[3,]    2   -1    8


In [ ]:
# Check the second eigenvector:
vect_1 <- A %*% A_P[1:3,2]
vect_2 <- A_D[2,2] * A_P[1:3,2]

cat("A.v2 = ")
print(vect_1)

cat("2.v2 = ")
print(vect_2)

A.v2 =           [,1]
[1,] 0.5831565
[2,] 1.7727425
[3,] 0.1010716
2.v2 = [1] 0.5831565 1.7727425 0.1010716


### 3.c - Singular value decomposition

Now we will discuss the built-in ***svd()*** function of R. Recall that given a (complex) $(n,m)$ matrix $M$, which is not necessarily square, its singular value decomposition (SVD) is written:
$$M = U\cdot\Sigma\cdot V^\dagger,$$
where:
* $U$ is an $(n,n)$ unitary matrix;
* $V$ is an $(m,m)$ unitary matrix ($V^\dagger$ is the Hermitian adjoint);
* $\Sigma$ is an $(n,m)$ rectangular diagonal matrix, whose entries are the **singular** values of $M$.

Note that the singular values of a matrix are non-negative. Their actual meaning will be discussed below. Note that generally speaking, the SVD of a matrix is computed by a least squares algorithm.

In [ ]:
# Make example matrix
M <- matrix(c(c(-3,2,1),c(2,1,5)), nrow = 2, byrow = TRUE)
M

[,1] [,2] [,3]
[1,] -3   2    1   
[2,]  2   1    5

In [ ]:
# Get SVD
M_SVD <- svd(M)
str(M_SVD)

List of 3
 $ d: num [1:2] 5.48 3.73
 $ u: num [1:2, 1:2] 0.0621 0.9981 0.9981 -0.0621
 $ v: num [1:3, 1:2] 0.33 0.205 0.921 -0.835 0.518 ...


Let us check the singular value decomposition:

In [ ]:
# M singular values and matrices
M_U <- M_SVD$u
M_V <- M_SVD$v
M_sig <- M_SVD$d

# Check singular value decomposition
cat("U.Sigma.V^t = ")
M_U %*% diag(M_sig) %*% t(M_V)

cat("U.U^t = ")
M_U %*% t(M_U)

cat("V^t.V = ")
t(M_V) %*% M_V # Weird: This is not a 3x3 matrix

U.Sigma.V^t = 

[,1] [,2] [,3]
[1,] -3   2    1   
[2,]  2   1    5

U.U^t = 

[,1] [,2]
[1,] 1    0   
[2,] 0    1

V^t.V = 

[,1]          [,2]         
[1,]  1.000000e+00 -8.326673e-17
[2,] -8.326673e-17  1.000000e+00

An interesting (numerical) linear algebra fact is the conditioning number of a matrix: If $\sigma_M$ is the set of singular values of $M$, then the condition number of a matrix is given by
$$\kappa_M = \frac{\max \sigma_M}{\min \sigma_M},$$
and the larger this number is, the larger will the numerical errors be. For our example:

In [ ]:
cat("kappa(M) = ")
max(M_sig)/min(M_sig)

kappa(M) = 

[1] 1.468637

Another useful fact is that the singular value decomposition allows to compute the **Moore-Penrose pseudo-inverse** of a matrix $M$. By definition, the pseudo-inverse $M^+$ should be a (generalized) **right** inverse of $M$. Using an SVD, we have:
$$M^+ = V\cdot\Sigma^+\cdot U^\dagger,$$
where  $\Sigma^+$ has the reciprocals of $\Sigma$ on its main diagonal. See:

https://search.r-project.org/CRAN/refmans/corpcor/html/pseudoinverse.html


In [ ]:
# Compute \Sigma^+
M_Sigma_plus <- matrix(c(c(1/M_sig[1], 0), c(0, 1/M_sig[2])),
                       nrow = 2, ncol =2, byrow = FALSE)
# Compute M^+
M_pinv <- M_V %*% M_Sigma_plus %*% t(M_U)

# Show result
cat("V.Sigma^+.U^t = ")
M_pinv

# Check M.M^+
cat("M.M^+ = ")
M %*% M_pinv

V.Sigma^+.U^t = 

[,1]        [,2]      
[1,] -0.21957041 0.07398568
[2,]  0.14081146 0.02863962
[3,]  0.05966587 0.16467780

M.M^+ = 

[,1]          [,2]         
[1,]  1.000000e+00 -5.551115e-17
[2,] -5.551115e-17  1.000000e+00

**Comment:** Finish the computations below. Relate the $U$ and $V$ matrices to the eigenvalues of $MM^\intercal$ and $M^\intercal M$.

In [ ]:
MMt <- M %*% t(M)
MtM <- t(M) %*% M

In [ ]:
MMt
MtM

[,1] [,2]
[1,] 14    1  
[2,]  1   30

[,1] [,2] [,3]
[1,] 13   -4    7  
[2,] -4    5    7  
[3,]  7    7   26

### 3.d - Solving linear systems

For this part, we briefly look at some functions in the *matlib*. The docs are here:

https://search.r-project.org/CRAN/refmans/corpcor/html/pseudoinverse.html

Here is an example on how to solve linear equations:

https://cran.r-project.org/web/packages/matlib/vignettes/linear-equations.html


In [ ]:
library(matlib)

First, we note that unlike the built-in matrix package, *matlib* has trace function and pseudo-inverse functions:

In [ ]:
# Trace of the matrix A:
cat("tr(A) = ")
tr(A)

# Pseudo-inverse of M:
cat("A.MoorePenrose(M) = ")
M %*% MoorePenrose(M)

tr(A) = 

[1] 13

A.MoorePenrose(M) = 

[,1]          [,2]         
[1,]  1.000000e+00 -5.551115e-17
[2,] -5.551115e-17  1.000000e+00

**Comment:** To be continued. The best place to start is the tutorial on linear equations above.