**NumPy Ultra Quick Tutorial**

A. J. Zerouali

2021/05/26

This is my notebook for Google's NumPy ultra quick refresher, found in the prerequisites of their machine learning Crash Course. The purpose is to familiarize myself the basic manipulations of tensor objects in Python.


In [5]:
#import tensorflow
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt

**Populating arrays with specific numbers**

In [6]:

vector_row = np.array([1, 2, 3, 4]) # This makes row vectors. How do you make column vectors?
vector_col = np.array([[1], [2], [3], [4]]) # This seems to make column vectors

In [7]:
print(vector_row)
print(vector_col) # The output is ugly for this one

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [8]:
matrix_3x3 = np.array([[0, -1, 0], [1, 0, 0], [1, 0, 0]])
print(matrix_3x3)

[[ 0 -1  0]
 [ 1  0  0]
 [ 1  0  0]]


**Remark:**

A little like Matlab in that you needn't declare/specify the type of variable before assigning values. 

**The "help" function**

Here's how you call for help in Python:

In [9]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

**Arrays with sequences and random numbers**

In [10]:
# Sequences of numbers: np.arange
print(np.arange(-1, 3)) # By default, the step is 1, and the obtained array doesn't include upper-bound. 


# "arange" is a fancier version of "range"
#print(range(-1,3))

[-1  0  1  2]


In [11]:
help(np.arange) # Let's see how this one is used...

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [12]:
vect_3 = np.arange(-0.1, 1.1, 0.1) # When you specify a step it seems to include the upper-bound (2nd argument)
print("np.arange((-0.1, 1.1, 0.1)) = ",vect_3)

np.arange((-0.1, 1.1, 0.1)) =  [-0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1]


In [13]:
# Random numbers: np.random.
# Remark: The help for numpy.random is humongous. It's a very sophisticated library of functions actually.
# help(np.random)

# np.randint(high=m, low=M, size=s) will generate an array of size s (could be a tensor) with numbers in [m, M-1]
print("numpy.random.randint(low=0, high=100, size=(10))= ", np.random.randint(low=0, high=100, size=(10)))
print("numpy.random.randint(low=0, high=100, size=(3,3)) = ", np.random.randint(low=0, high=100, size=(3,3)))

numpy.random.randint(low=0, high=100, size=(10))=  [24 63 82 32 51 37 40 14 98 20]
numpy.random.randint(low=0, high=100, size=(3,3)) =  [[12 47 63]
 [21 38 69]
 [49 11 61]]


In [14]:
# np.random.random(s) will generate a vector with s floats in [0, 1[
print("np.random.random(3) =", np.random.random(3))

np.random.random(3) = [0.56114427 0.05688494 0.4110396 ]


**Linear Algebra Manipulations**

Here's one difference with Matlab: Python doesn't return an error if we try to add/multiply tensors of different sizes (why though?). There's a built-in "broadcasting" method that resizes the variables to usable shapes.

In [15]:
# Below are some tests with basic trig functions in NumPy
#help(np.sin)
pi=np.pi
print("cos(pi/2) = ", np.cos(pi/2)) # Doesn't return 0... stupid numerical approximations
print("sin(pi/2) = ", np.sin(pi/2))
print("tan(pi/4) = ", np.tan(pi/4))
print("tan(-pi/2) = ", np.tan(-pi/2))

cos(pi/2) =  6.123233995736766e-17
sin(pi/2) =  1.0
tan(pi/4) =  0.9999999999999999
tan(-pi/2) =  -1.633123935319537e+16


In [16]:
# Some basic matrix operations. I'm keeping the pi = np.pi used above
xy_Rot_pi = np.array([[np.cos(pi), np.sin(pi), 0], [np.sin(pi), np.cos(pi), 0], [0, 0, 1]])
e_1 = np.array([[1], [0], [0]])
e_2 = np.array([[0], [1], [0]])
e_3 = np.array([[0], [0], [1]])
#print("Broadcasting doesn't preserve the size of matrices:")
#print("xy_Rot_pi*e_1 =", xy_Rot_pi*e_1) # Broadcasting doesn't preserve the size of matrices
#print("If we want the correct mathematical output:")
#print("xy_Rot_pi*e_1 =", xy_Rot_pi*e_1)
# Amine says that you should use ".dot()", as below:
#print("xy_Rot_pi .* e_1 =", xy_Rot_pi .dot(e_1))

In [17]:
import decimal
decimal.getcontext().prec=3

In [19]:
print(2*pi)

6.283185307179586
